services:
  centos7:
    image: centos/python-38-centos7
    container_name: centos7
    platform: linux/amd64
    networks:
      - ansible-net
    command: sleep infinity 

  ubuntu:
    image: ubuntu:20.04
    container_name: ubuntu
    networks:
      - ansible-net
    command: sleep infinity

networks:
  ansible-net:
    driver: bridge